name: cbo_report
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.66.0
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  fluttertoast: ^8.2.4
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/Cooplogo.png